name: Build & Push to GHCR

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/abhinavmoosaramtota/todoapp


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: Build image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push SHA tag
        run: docker push $IMAGE_NAME:${{ github.sha }}

      - name: Tag & push latest
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
